apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-master-0
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/data/mydata/redis/redis_master_0"
    server: "10.16.150.138"
