apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-replica-1
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/data/mydata/redis/redis_replicas_1"
    server: "10.16.150.138"

