apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2
spec:
  storageClassName: sonstorageclass
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/data/mydata/"
    server: "10.16.150.138"
