---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-user
type: kubernetes.io/basic-auth
data:
  password: <base64 son123aA@> 
  username: <base64 son>
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-superuser
type: kubernetes.io/basic-auth
data:
  password: <base64 son123aA@>
  username: <base64 postgres>
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-backup-creds
data:
  ACCESS_KEY_ID: <base64 Bigdata Access Key ID>
  ACCESS_SECRET_KEY: <base64 Bigdata Access Secret Key>
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-cnpg
spec:
  description: "Cluster CNPG"
  imageName: ghcr.io/cloudnative-pg/postgresql:15.4
  instances: 3
  startDelay: 300
  stopDelay: 300
  primaryUpdateStrategy: unsupervised

  postgresql:
    parameters:
      shared_buffers: 256MB
      pg_stat_statements.max: '10000'
      pg_stat_statements.track: all
      auto_explain.log_min_duration: '10s'
    pg_hba:
      - host all all 10.244.0.0/16 md5

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: cluster-user

  superuserSecret:
    name: cluster-superuser

  storage:
    storageClass: standard
    size: 1Gi

  backup:
    barmanObjectStore:
      destinationPath: s3://cluster-cnpg-backup/
      endpointURL: http://microk8s-hl:9000
      s3Credentials:
        accessKeyId:
          name: minio-backup-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: minio-backup-creds
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
        encryption: AES256
      data:
        compression: gzip
        encryption: AES256
        immediateCheckpoint: false
        jobs: 2
    retentionPolicy: "30d"

  resources:
    requests:
      memory: "512Mi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "2"

  affinity:
    enablePodAntiAffinity: true
    topologyKey: failure-domain.beta.kubernetes.io/zone

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: false
