apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-rgw-son-s3-store-nodeport
  namespace: rook-ceph
spec:
  type: NodePort
  selector:
    app: rook-ceph-rgw
    rook_cluster: rook-ceph
    rook_object_store: son-s3-store
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
