apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-for-postgres-ha-1
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/data/mydata/db_1"
    server: "10.16.150.138"
