apiVersion: apps/v1
kind: Deployment
metadata:
  name: meetui-deployment
spec:
  replicas: 3 # Number of replicas
  selector:
    matchLabels:
      app: meetui
  template:
    metadata:
      labels:
        app: meetui
    spec:
      containers:
        - name: meetui
          image: meeting.v3/ui:25122023_094551
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000 # Your application's port

---
apiVersion: v1
kind: Service
metadata:
  name: meetui-service
spec:
  type: NodePort
  selector:
    app: meetui
  ports:
    - port: 3000 # Port accessible inside the cluster
      targetPort: 3000 # Container port to forward to
      nodePort: 30007 # Optional: Specific nodePort, otherwise Kubernetes will allocate one
