apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-release-influxdb-data-my-release-influxdb-0
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: manual
