apiVersion: v1
kind: ServiceAccount
metadata:
  name: influxdb-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: influxdb-role
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: influxdb-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: influxdb-sa
  namespace: default
roleRef:
  kind: Role
  name: influxdb-role
  apiGroup: rbac.authorization.k8s.io
