apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: operator
    meta.helm.sh/release-namespace: minio-operator
  creationTimestamp: "2024-03-18T13:39:30Z"
  labels:
    app.kubernetes.io/instance: operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: operator
    app.kubernetes.io/version: v5.0.14
    helm.sh/chart: operator-5.0.14
  name: console
  namespace: minio-operator
  resourceVersion: "18322552"
  uid: 615b6679-7718-4bd7-b3c2-b22951dab556
spec:
  clusterIP: 10.98.43.108
  clusterIPs:
  - 10.98.43.108
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: 30090  # Add this line
  - name: https
    port: 9443
    protocol: TCP
    targetPort: 9443
  selector:
    app.kubernetes.io/instance: operator-console
    app.kubernetes.io/name: operator
  sessionAffinity: None
  type: NodePort  # Change this from ClusterIP to NodePort
status:
  loadBalancer: {}
