apiVersion: v1
kind: Service
metadata:
  name: console
  # Include other metadata if necessary
spec:
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: 30090
  type: NodePort
